export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const LOGOUT = 'LOGOUT'

export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS'
export const UPLOAD_START = 'UPLOAD_START'
export const UPLOAD_FAIL = 'UPLOAD_FAIL'

export const RETREIVING_SUCCESS = 'RETREIVING_SUCCESS'
export const RETREIVING_START = 'RETREIVING_START'
export const RETREIVING_FAIL = 'RETREIVING_FAIL'

export const UPDATE_START = 'UPDATE_START'
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAIL = 'UPDATE_FAIL'

export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'
